version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www/html
    env_file:
      - .env  # Load environment variables from the local .env file
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Ecommercemarolix
      MYSQL_DATABASE: ecommerce_marolix
      MYSQL_USER: marolix
      MYSQL_PASSWORD: Ecommercemarolix
