version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env  # Load environment variables from the local .env file
    environment:
      - DB_HOST=db
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ecommercemarolix
      MYSQL_DATABASE: ecommerce_marolix
      MYSQL_USER: marolix
      MYSQL_PASSWORD: Ecommercemarolix
